"""add menu_confirmed to parties

Revision ID: c8f5a8498408
Revises: a7c8cef51dbe
Create Date: 2026-10-05 11:07:18.858431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f5a8498408'
down_revision: Union[str, Sequence[str], None] = 'a7c8cef51dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('menu_confirmed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parties', 'menu_confirmed')
    # ### end Alembic commands ###
